# Generated by Django 5.2.1 on 2025-06-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='Math', max_length=50, verbose_name='category'),
        ),
    ]
