# Generated by Django 5.2.1 on 2025-06-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(upload_to='cinema/static/cinema/pictures', verbose_name='preview'),
        ),
    ]
