# Generated by Django 5.2.4 on 2025-07-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_video_preview_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
    ]
