# Generated by Django 5.2.4 on 2025-07-15 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(default=None, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'PNG'])], verbose_name='preview'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'wmv'])], verbose_name='file'),
        ),
    ]
