# Generated by Django 5.2.1 on 2025-07-22 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_alter_video_preview_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Math', 'Math'), ('Geometry', 'Geometry'), ('Physics', 'Physics'), ('Algebra', 'Algebra')], default='Math', max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'PNG', 'webp'])], verbose_name='preview'),
        ),
    ]
